import shrineFigures from '../../data/kg-shrine-figures.json';
import compositeFigures from '../../data/kg-composite-figures.json';

/**
 * Shrine slug → the figures commemorated there, most-principal first.
 *
 * A deliberate 11 KB duplicate of one edge type out of the 426 KB knowledge
 * graph. ShrinePage needs exactly one fact from the graph — the slug of the
 * shrine's named figure, for a link to that figure's entity page — and
 * importing `lib/kg.ts` for it pulled the whole 317 KB graph chunk onto the
 * archive's hottest route. Measured 20 August 2026: 40% of `/shrine/<slug>`'s
 * eager JavaScript, for one `href`.
 *
 * Generated by `scripts/data/build-kg.mjs` from the same `buried_at` relations
 * `getSaintsForShrine()` reads, and held to that by
 * `src/lib/__tests__/kgShrineFigures.test.ts` — which compares the index
 * against the graph for every shrine, so the two cannot drift silently.
 *
 * Slugs only, on purpose. Adding names would put every figure's display string
 * (and its Urdu) back on the wire and undo the saving.
 */
const INDEX = shrineFigures as Record<string, string[]>;
const COMPOSITE = compositeFigures as Record<string, CompositeFigure[]>;

/** Figure slugs commemorated at a shrine, in the graph's own order. */
export function figureSlugsForShrine(shrineSlug: string): string[] {
  return INDEX[shrineSlug] ?? [];
}

/** The shrine's principal figure, or undefined when the graph records none. */
export function primaryFigureSlug(shrineSlug: string): string | undefined {
  return INDEX[shrineSlug]?.[0];
}

/**
 * A figure named on a shrine's row, with the name the graph knows it by.
 *
 * `name` is the canonical figure name, not the sheet's raw cell — see
 * `compositeFiguresForShrine`.
 */
export interface CompositeFigure {
  readonly slug: string;
  readonly name: string;
}

/**
 * The figures named by a row that names more than one, primary first.
 *
 * Three rows out of 169 record a site held by two people: Gurdwara Panjvi Chati
 * Patshahi is the fifth *and* sixth Guruship, Rori Sahib is Guru Nanak *and*
 * Bhai Mardana, Khoohi Bhai Lalo is Guru Nanak *and* Bhai Lalo. Every handling
 * of them before 28 August 2026 lost one of the two, and for Rori Sahib the one
 * lost was Bhai Mardana, who was consequently absent from the graph entirely.
 *
 * Empty for the other 166 rows, which is the signal to render the single link
 * `primaryFigureSlug` already supports.
 *
 * **Why this carries names when `figureSlugsForShrine` deliberately does not.**
 * A second figure needs a second label, and there is no honest way to derive one
 * from a slug — title-casing `guru-arjan-dev` happens to work and
 * `shrine-of-baba-shah-kamal` becomes "Shrine Of Baba Shah Kamal". So the name
 * is carried, for the three rows that need it and no others: 558 bytes, against
 * the display string and its Urdu for all 190 figures if the main index grew a
 * name column.
 */
export function compositeFiguresForShrine(shrineSlug: string): readonly CompositeFigure[] {
  return COMPOSITE[shrineSlug] ?? [];
}
