import shrineFigures from '../../data/kg-shrine-figures.json';
import figureLabels from '../../data/kg-shrine-figure-labels.json';

/**
 * Shrine slug → the figures commemorated there, most-principal first.
 *
 * A deliberate 11 KB duplicate of one edge type out of the 426 KB knowledge
 * graph. ShrinePage needs exactly one fact from the graph — the slug of the
 * shrine's named figure, for a link to that figure's entity page — and
 * importing `lib/kg.ts` for it pulled the whole 317 KB graph chunk onto the
 * archive's hottest route. Measured 20 August 2026: 40% of `/shrine/<slug>`'s
 * eager JavaScript, for one `href`.
 *
 * Generated by `scripts/data/build-kg.mjs` from the same `buried_at` relations
 * `getSaintsForShrine()` reads, and held to that by
 * `src/lib/__tests__/kgShrineFigures.test.ts` — which compares the index
 * against the graph for every shrine, so the two cannot drift silently.
 *
 * Slugs only, on purpose. Adding names would put every figure's display string
 * (and its Urdu) back on the wire and undo the saving.
 */
const INDEX = shrineFigures as Record<string, string[]>;
const LABELS = figureLabels as Record<string, ShrineFigureLabel[]>;

/** Figure slugs commemorated at a shrine, in the graph's own order. */
export function figureSlugsForShrine(shrineSlug: string): string[] {
  return INDEX[shrineSlug] ?? [];
}

/** The shrine's principal figure, or undefined when the graph records none. */
export function primaryFigureSlug(shrineSlug: string): string | undefined {
  return INDEX[shrineSlug]?.[0];
}

/**
 * A figure a shrine commemorates, with the name the graph knows it by.
 *
 * `name` is the canonical figure name, not the sheet's raw cell — see
 * `figureLabelsForShrine`.
 */
export interface ShrineFigureLabel {
  readonly slug: string;
  readonly name: string;
}

/**
 * The figures to render for a shrine whose `Sufi Saint` cell is not a usable
 * label, primary first. Empty for the 165 rows where the cell is fine.
 *
 * Two kinds of row are in here, and they are one problem — the cell does not
 * name what the page must link to:
 *
 *  - **It names two people.** Three rows record a site held by two: Gurdwara
 *    Panjvi Chati Patshahi is the fifth *and* sixth Guruship, Rori Sahib is Guru
 *    Nanak *and* Bhai Mardana, Khoohi Bhai Lalo is Guru Nanak *and* Bhai Lalo.
 *    Every handling of them before 28 August 2026 lost one of the two, and for
 *    Rori Sahib the one lost was Bhai Mardana, who was absent from the graph
 *    entirely.
 *  - **It names somebody else.** Tomb of Javindi Bibi's cell reads "Jalaluddin
 *    Surkh-Posh Bukhari" — byte-identical to the cell on his own shrine, a
 *    different monument. `saintFigureByShrine` points the graph at Bibi Jawindi;
 *    without this the page would print his name over a link to her page, which
 *    is worse than the error it replaced, because the name and the link agreed
 *    before and disagree after.
 *
 * **Why this carries names when `figureSlugsForShrine` deliberately does not.**
 * There is no honest way to derive a display name from a slug — title-casing
 * `guru-arjan-dev` happens to work and `shrine-of-baba-shah-kamal` becomes
 * "Shrine Of Baba Shah Kamal". So the name is carried, for the four rows that
 * need it and no others: under a kilobyte, against the display string and its
 * Urdu for all 191 figures if the main index grew a name column.
 */
export function figureLabelsForShrine(shrineSlug: string): readonly ShrineFigureLabel[] {
  return LABELS[shrineSlug] ?? [];
}
