import shrineFigures from '../../data/kg-shrine-figures.json';

/**
 * Shrine slug → the figures commemorated there, most-principal first.
 *
 * A deliberate 11 KB duplicate of one edge type out of the 426 KB knowledge
 * graph. ShrinePage needs exactly one fact from the graph — the slug of the
 * shrine's named figure, for a link to that figure's entity page — and
 * importing `lib/kg.ts` for it pulled the whole 317 KB graph chunk onto the
 * archive's hottest route. Measured 20 August 2026: 40% of `/shrine/<slug>`'s
 * eager JavaScript, for one `href`.
 *
 * Generated by `scripts/data/build-kg.mjs` from the same `buried_at` relations
 * `getSaintsForShrine()` reads, and held to that by
 * `src/lib/__tests__/kgShrineFigures.test.ts` — which compares the index
 * against the graph for every shrine, so the two cannot drift silently.
 *
 * Slugs only, on purpose. Adding names would put every figure's display string
 * (and its Urdu) back on the wire and undo the saving.
 */
const INDEX = shrineFigures as Record<string, string[]>;

/** Figure slugs commemorated at a shrine, in the graph's own order. */
export function figureSlugsForShrine(shrineSlug: string): string[] {
  return INDEX[shrineSlug] ?? [];
}

/** The shrine's principal figure, or undefined when the graph records none. */
export function primaryFigureSlug(shrineSlug: string): string | undefined {
  return INDEX[shrineSlug]?.[0];
}
