#!/usr/bin/env python3
"""Record what the shipped Nastaliq faces can draw.

Why this exists (RULE 4). The Urdu reading face is **Mehr Nastaliq Web**, which
maps 108 codepoints. Noto Nastaliq Urdu, which sits behind it in `--font-urdu`,
maps 333. Per-glyph fallback means a character Mehr lacks is still drawn in a
Nastaliq — but in a *different* Nastaliq, and Nastaliq is a connected script, so
the join breaks in the middle of the word. Today that happens three times in the
whole archive, all inside quoted verse:

    U+0768  ݨ  Punjabi/Saraiki noon with small tah  (Bulleh Shah)
    U+066D  ٭  hemistich separator                  (Lal Shahbaz Qalandar)
    U+0680  ڀ  Sindhi beheh                         (Shah Abdul Latif)

A fourth would be a visible defect nobody would think to look for, so
`src/styles/__tests__/nastaliqCoverage.test.ts` holds the corpus against this
manifest on every `npm run verify`. Vitest cannot parse WOFF2 (brotli plus the
format's own table transform, and the repo carries no font parser), so the cmap
is extracted here, with fontTools, and checked in. The manifest records the
font's SHA-256: replace the font without re-running this and the test fails
telling you to.

Usage:
    python3 pipeline/build_nastaliq_coverage.py           # write the manifest
    python3 pipeline/build_nastaliq_coverage.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import unicodedata
from pathlib import Path

from fontTools.ttLib import TTFont

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "pipeline" / "nastaliq_coverage.json"
FONTS = {
    "Mehr Nastaliq Web": "public/fonts/MehrNastaliqWeb.woff2",
    "Noto Nastaliq Urdu": "public/fonts/NotoNastaliqUrdu-400.woff2",
}


def build() -> dict:
    out: dict = {
        "_comment": (
            "Generated by pipeline/build_nastaliq_coverage.py. Do not hand-edit — "
            "re-run the script. Held by src/styles/__tests__/nastaliqCoverage.test.ts."
        ),
        "fonts": {},
    }
    for family, rel in FONTS.items():
        path = REPO / rel
        raw = path.read_bytes()
        cmap = sorted(TTFont(path).getBestCmap())
        out["fonts"][family] = {
            "file": rel,
            "bytes": len(raw),
            "sha256": hashlib.sha256(raw).hexdigest(),
            "codepoints": [f"{cp:04X}" for cp in cmap],
        }
    mehr = set(out["fonts"]["Mehr Nastaliq Web"]["codepoints"])
    noto = set(out["fonts"]["Noto Nastaliq Urdu"]["codepoints"])
    fallback = sorted(noto - mehr)
    out["servedByFallback"] = [
        {
            "codepoint": cp,
            "char": chr(int(cp, 16)),
            "name": name(int(cp, 16)),
        }
        for cp in fallback
    ]
    return out


def name(cp: int) -> str:
    try:
        return unicodedata.name(chr(cp))
    except ValueError:
        return "<unnamed>"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the manifest is stale")
    args = ap.parse_args()

    fresh = build()
    if args.check:
        if not MANIFEST.exists():
            print(f"[nastaliq-coverage] MISSING {MANIFEST.relative_to(REPO)}", file=sys.stderr)
            return 1
        current = json.loads(MANIFEST.read_text(encoding="utf-8"))
        if current.get("fonts") != fresh["fonts"]:
            print(
                "[nastaliq-coverage] STALE — a font file changed. Re-run:\n"
                "    python3 pipeline/build_nastaliq_coverage.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"[nastaliq-coverage] OK — {len(fresh['fonts'])} face(s) recorded, "
            f"{len(fresh['servedByFallback'])} codepoint(s) served by the fallback face."
        )
        return 0

    MANIFEST.write_text(json.dumps(fresh, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    for family, rec in fresh["fonts"].items():
        print(f"[nastaliq-coverage] {family}: {len(rec['codepoints'])} codepoints, {rec['bytes']} bytes")
    print(f"[nastaliq-coverage] wrote {MANIFEST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
