# -*- coding: utf-8 -*-
"""
update_log.py — regenerates urdu-i18n/TRANSLATION_LOG.md from the actual state on
disk: which shrines have a content/<slug>.md (done) vs. which still need one.

Run any time (also called by build-all.sh). This is the resumable source of truth
— if a session ends mid-way, re-read this log to see exactly what remains.
"""
import json, os, glob, datetime

OUT = os.path.dirname(os.path.abspath(__file__))

# shrines with NO English description yet (can't translate until sourced).
# (2026-07-10: the 8 formerly listed here — Shah Yousuf, Guru Gurpat Mandir,
# Bhai Sant Thawan Das Mandir, Jhollay Lal Mandir, Gurdas Ram Mandir, Gurdwara
# Sach Khand Sahib, Gurdwara Dash Mesh Pita, Jagannath Temple Sialkot — all
# received sourced English descriptions in the M1/M2 dataset-integrity pass
# and are now unblocked; they appear in `_english_descriptions.json` and the
# Remaining list below like any other untranslated shrine.)
BLOCKED = []


def load_english():
    with open(os.path.join(OUT, "_english_descriptions.json"), encoding="utf-8") as f:
        return json.load(f)


def load_tour_slugs():
    """Tour-featured shrines get priority."""
    tour_slugs = set()
    try:
        tours_path = os.path.normpath(os.path.join(OUT, "..", "src", "data", "tours.json"))
        with open(tours_path, encoding="utf-8") as f:
            tours = json.load(f)
        for t in tours:
            for s in t.get("stops", []):
                tour_slugs.add(s["shrineSlug"])
    except Exception:
        pass
    return tour_slugs


def load_done_slugs():
    done = set()
    for p in glob.glob(os.path.join(OUT, "content", "*.md")):
        with open(p, encoding="utf-8") as f:
            if f.read().strip():
                done.add(os.path.splitext(os.path.basename(p))[0])
    return done


def main():
    ENG = load_english()
    tour_slugs = load_tour_slugs()
    done = load_done_slugs()

    translatable = list(ENG.keys())
    done_t = [s for s in translatable if s in done]
    remaining = [s for s in translatable if s not in done]
    # priority: tour shrines first, then longer (more prominent) descriptions first
    remaining.sort(key=lambda s: (s not in tour_slugs, -len(ENG[s]["desc"])))

    total = len(translatable)
    pct = round(100 * len(done_t) / total) if total else 0

    L = []
    L.append("# Urdu translation log")
    L.append("")
    L.append(f"_Auto-generated by `update_log.py` · {datetime.date.today().isoformat()}_")
    L.append("")
    L.append(f"**Progress: {len(done_t)} / {total} shrine descriptions translated ({pct}%).** "
             f"{len(BLOCKED)} more are blocked (no English description yet).")
    L.append("")
    L.append("## How to resume")
    L.append("")
    L.append("Each shrine's Urdu article lives in `urdu-i18n/content/<slug>.md` (native Urdu, "
             "`## Heading` structure mirroring the English, numbers left Western). The English "
             "source for every shrine is in `urdu-i18n/_english_descriptions.json` "
             "(`{slug: {name, category, desc}}`). To continue: pick the next slug under "
             "**Remaining**, read its English from that JSON, author `content/<slug>.md`, then "
             "run `npm run urdu:build` (which rebuilds + revalidates + refreshes this log).")
    L.append("")
    L.append(f"## Remaining ({len(remaining)}) — priority order (★ = guided-tour shrine)")
    L.append("")
    L.append("| # | slug | shrine | category | en chars |")
    L.append("|---|------|--------|----------|----------|")
    for i, s in enumerate(remaining, 1):
        star = "★ " if s in tour_slugs else ""
        L.append(f"| {i} | `{s}` | {star}{ENG[s]['name']} | {ENG[s]['category']} | {len(ENG[s]['desc'])} |")
    L.append("")
    L.append(f"## Done ({len(done_t)})")
    L.append("")
    for s in sorted(done_t):
        L.append(f"- [x] `{s}` — {ENG[s]['name']}")
    L.append("")
    L.append(f"## Blocked — no English description ({len(BLOCKED)})")
    L.append("")
    L.append("These need a sourced English description first (see `TODO.md` §1–§2); "
             "some are duplicates/renames to resolve before writing.")
    L.append("")
    for n in BLOCKED:
        L.append(f"- [ ] {n}")
    L.append("")

    with open(os.path.join(OUT, "TRANSLATION_LOG.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"[update_log] {len(done_t)}/{total} done ({pct}%), {len(remaining)} remaining, {len(BLOCKED)} blocked.")


if __name__ == "__main__":
    main()
