import argparse
import csv
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request


DEFAULT_CSV_URL = (
    "https://docs.google.com/spreadsheets/d/e/"
    "2PACX-1vSmsEsQclqJuEioIHxQa6ZaTf1SmSuKhM-B3RcfEQyK8Ewqy4-c_xe7DOgBWdhMUyvtrzThIVl9Y9df/"
    "pub?gid=0&single=true&output=csv"
)
DEFAULT_LIBRETRANSLATE_URL = "http://127.0.0.1:5000/translate"
SKIP_COLUMNS = {
    "Latitude",
    "Longitude",
    "Image Link",
    "Image",
    "image",
    "image_url",
    "photo",
    "photo_url",
}


def is_likely_url(value: str) -> bool:
    return value.startswith("http://") or value.startswith("https://") or value.startswith(
        "www."
    )


def should_translate(value: str) -> bool:
    if not value:
        return False
    if is_likely_url(value):
        return False
    if not re.search(r"[A-Za-z]", value):
        return False
    return True


def fetch_csv_rows(csv_url: str) -> list[dict]:
    with urllib.request.urlopen(csv_url) as response:
        data = response.read().decode("utf-8")
    reader = csv.DictReader(data.splitlines())
    rows = []
    for row in reader:
        cleaned = {str(k).strip(): (str(v).strip() if v is not None else "") for k, v in row.items()}
        rows.append(cleaned)
    return rows


def collect_phrases(rows: list[dict]) -> list[str]:
    phrases: set[str] = set()
    for row in rows:
        for key, value in row.items():
            if not key:
                continue
            if key in SKIP_COLUMNS:
                continue
            if re.search(r"urdu|_ur|\(urdu\)|\bur\b", key, flags=re.IGNORECASE):
                continue
            if should_translate(key):
                phrases.add(key)
            if should_translate(value):
                phrases.add(value)
    return sorted(phrases)


def libre_translate(text: str, endpoint: str) -> str:
    payload = json.dumps(
        {
            "q": text,
            "source": "en",
            "target": "ur",
            "format": "text",
        }
    ).encode("utf-8")

    request = urllib.request.Request(
        endpoint,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    with urllib.request.urlopen(request) as response:
        raw = response.read().decode("utf-8")
    parsed = json.loads(raw)
    translated = str(parsed.get("translatedText", "")).strip()
    return translated or text


def write_translations_js(output_path: str, translations: dict[str, str]) -> None:
    content = [
        "// Generated by build_translation_cache.py",
        "window.SHRINE_TRANSLATIONS = {",
    ]
    for key in sorted(translations.keys(), key=str.lower):
        value = translations[key]
        content.append(
            f"  {json.dumps(key, ensure_ascii=False)}: {json.dumps(value, ensure_ascii=False)},"
        )
    content.append("};")
    content.append("")

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(content))


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Translate shrine content once using a self-hosted LibreTranslate endpoint "
            "and write translations.js for offline use."
        )
    )
    parser.add_argument("--csv-url", default=DEFAULT_CSV_URL, help="CSV URL to read rows from")
    parser.add_argument(
        "--libre-url",
        default=DEFAULT_LIBRETRANSLATE_URL,
        help="LibreTranslate /translate endpoint URL",
    )
    parser.add_argument(
        "--output",
        default="translations.js",
        help="Output JS file path",
    )
    args = parser.parse_args()

    try:
        rows = fetch_csv_rows(args.csv_url)
    except urllib.error.URLError as exc:
        print(f"Failed to fetch CSV: {exc}", file=sys.stderr)
        return 1

    phrases = collect_phrases(rows)
    if not phrases:
        print("No translatable phrases found.")
        write_translations_js(args.output, {})
        return 0

    translations: dict[str, str] = {}
    for idx, phrase in enumerate(phrases, start=1):
        try:
            translated = libre_translate(phrase, args.libre_url)
        except urllib.error.URLError as exc:
            print(
                "Failed to reach LibreTranslate endpoint.\n"
                f"Endpoint: {args.libre_url}\n"
                f"Error: {exc}",
                file=sys.stderr,
            )
            return 1
        except json.JSONDecodeError as exc:
            print(f"Invalid JSON response for phrase '{phrase}': {exc}", file=sys.stderr)
            return 1

        translations[phrase] = translated
        if idx % 25 == 0 or idx == len(phrases):
            print(f"Translated {idx}/{len(phrases)} phrases...")

    write_translations_js(args.output, translations)
    print(f"Wrote {len(translations)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
